export default [
  {
      "records": [
          {
              "_id": "60ae575925965f75b70d862f",
              "number": 2,
              "chrc": true,
              "sele": {
                  "color": "blue",
                  "value": "Tes"
              },
              "ms": null,
              "phone": null,
              "emails": "asss",
              "urls": "aa",
              "currs": null,
              "perc": 0.22,
              "rating": 5,
              "durr": null,
              "Name": "aaa",
              "sss": 14,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "hello",
              "update ats": "2021-07-17T07:54:28.402Z",
              "nnnnn": 12,
              "file": [
                  {
                      "url": "https://pbs.twimg.com/profile_images/805651234698842112/uPSrYOHT.jpg",
                      "fileName": "uPSrYOHT.jpg"
                  }
              ],
              "rat": 2,
              "note": "asdassss",
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [
                  "60d5ab4d49d2fb312ceddc62",
                  "60d5aba0bd50c764f65fbc13",
                  "60d5ae70bd50c764f65fbc21",
                  "60d698b10a5b7ac68c4a82bc"
              ],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          },
          {
              "_id": "60ae576c25965f75b70d8642",
              "number": 11,
              "chrc": true,
              "sele": {
                  "color": "blue",
                  "value": "sss"
              },
              "ms": [
                  {
                      "value": "sss",
                      "color": "blue"
                  }
              ],
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": 5,
              "durr": null,
              "Name": "ss",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": "2021-07-23T03:24:42.555Z",
              "nnnnn": null,
              "file": null,
              "rat": 4,
              "note": "wsss",
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          }
      ],
      "count": 2,
      "groupBy": {
          "rating": 5
      }
  },
  {
      "records": [
          {
              "_id": "60ae576625965f75b70d863c",
              "number": 8,
              "chrc": true,
              "sele": {
                  "color": "blue",
                  "value": "Tes"
              },
              "ms": null,
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": 6,
              "durr": null,
              "Name": "asass",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "nona",
              "update ats": "2021-07-17T07:53:25.539Z",
              "nnnnn": null,
              "file": null,
              "rat": 5,
              "note": "aku siap",
              "tanggal": "2021-07-08T07:53:00.000Z",
              "user": [],
              "email": [],
              "tes 2": [
                  "60d5ae70bd50c764f65fbc21"
              ],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          }
      ],
      "count": 1,
      "groupBy": {
          "rating": 6
      }
  },
  {
      "records": [
          {
              "_id": "60ae575d25965f75b70d8633",
              "number": 4,
              "chrc": true,
              "sele": {
                  "color": "blue",
                  "value": "ccc"
              },
              "ms": null,
              "phone": "342423",
              "emails": null,
              "urls": "google.com",
              "currs": "",
              "perc": null,
              "rating": null,
              "durr": 10,
              "Name": "d",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": "2021-07-17T01:21:14.521Z",
              "nnnnn": null,
              "file": null,
              "rat": 4,
              "note": "ssssasdasda",
              "tanggal": "2021-07-16T19:19:05.126Z",
              "user": [
                  "60b18511ef23e310a8f7c086"
              ],
              "email": [
                  "a.aswara+2@gmail.com"
              ],
              "tes 2": [
                  "60e5d4774cb448de481a84c5"
              ],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          },
          {
              "_id": "60ae576225965f75b70d8638",
              "number": 6,
              "chrc": null,
              "sele": {
                  "color": "blue",
                  "value": "sss"
              },
              "ms": null,
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": 0.1,
              "rating": null,
              "durr": null,
              "Name": "asdsada",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": "2021-07-17T07:53:14.425Z",
              "nnnnn": 123,
              "file": null,
              "rat": 2,
              "note": "selamat datang",
              "tanggal": "2021-07-16T07:53:00.000Z",
              "user": [
                  "60b18511ef23e310a8f7c086"
              ],
              "email": [
                  "a.aswara+2@gmail.com"
              ],
              "tes 2": [],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          },
          {
              "_id": "60ae576425965f75b70d863a",
              "number": 7,
              "chrc": null,
              "sele": {
                  "color": "blue",
                  "value": "Tes"
              },
              "ms": [
                  {
                      "color": "blue",
                      "value": "sss"
                  }
              ],
              "phone": "hello",
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "fsdfdf",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": "2021-07-17T00:32:27.242Z",
              "nnnnn": 12,
              "file": null,
              "rat": 3,
              "note": "selamat data",
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [
                  "60e5d4774cb448de481a84c5"
              ],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          },
          {
              "_id": "60ae576a25965f75b70d8640",
              "number": 10,
              "chrc": null,
              "sele": {
                  "color": "blue",
                  "value": "ccc"
              },
              "ms": [
                  {
                      "color": "blue",
                      "value": "aa"
                  },
                  {
                      "color": "blue",
                      "value": "sss"
                  }
              ],
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "aaaaaa",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": "2021-07-17T07:52:41.264Z",
              "nnnnn": null,
              "file": [
                  {
                      "url": "https://api.staging.kontenbase.com/upload/file/60ae570f25965f75b70d8615/dRSMKztnPivdvUX/globe.png",
                      "fileName": "globe.png"
                  }
              ],
              "rat": 4,
              "note": "hello world",
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          },
          {
              "_id": "60ae576e25965f75b70d8644",
              "number": 12,
              "chrc": null,
              "sele": {
                  "color": "blue",
                  "value": "sss"
              },
              "ms": null,
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "sssss",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": "2021-07-17T07:53:00.754Z",
              "nnnnn": null,
              "file": null,
              "rat": 5,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          },
          {
              "_id": "60ae577125965f75b70d8646",
              "number": 13,
              "chrc": true,
              "sele": {
                  "color": "blue",
                  "value": "Tes"
              },
              "ms": null,
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": 1232,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "d",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": "2021-07-23T03:24:47.903Z",
              "nnnnn": -3,
              "file": null,
              "rat": 5,
              "note": "asdsad",
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          },
          {
              "_id": "60e30b4a4cb448de481a836b",
              "number": 17,
              "chrc": null,
              "sele": {
                  "color": "blue",
                  "value": "sss"
              },
              "ms": null,
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "sss",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": "2021-07-19T01:19:05.288Z",
              "nnnnn": 4,
              "file": null,
              "rat": 2,
              "note": null,
              "tanggal": null,
              "user": [
                  "60b18511ef23e310a8f7c086"
              ],
              "email": [
                  "a.aswara+2@gmail.com"
              ],
              "tes 2": [],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          },
          {
              "_id": "60e30b594cb448de481a836e",
              "number": 18,
              "chrc": true,
              "sele": {
                  "color": "blue",
                  "value": "sss"
              },
              "ms": null,
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "tes",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": "2021-07-23T03:24:44.576Z",
              "nnnnn": null,
              "file": null,
              "rat": null,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          },
          {
              "_id": "60e30b5d4cb448de481a8371",
              "number": 19,
              "chrc": null,
              "sele": null,
              "ms": null,
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "aaa",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": null,
              "nnnnn": null,
              "file": null,
              "rat": null,
              "note": null,
              "tanggal": null,
              "user": [
                  "60b18511ef23e310a8f7c086"
              ],
              "email": [
                  "a.aswara+2@gmail.com"
              ],
              "tes 2": [],
              "createdby": null,
              "updated": null
          },
          {
              "_id": "60e30b5d4cb448de481a8373",
              "number": 20,
              "chrc": null,
              "sele": null,
              "ms": null,
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "ssss",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": null,
              "nnnnn": null,
              "file": null,
              "rat": null,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": null
          },
          {
              "_id": "60e30b5d4cb448de481a8375",
              "number": 21,
              "chrc": null,
              "sele": null,
              "ms": null,
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "asd",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": null,
              "nnnnn": null,
              "file": null,
              "rat": null,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": null
          },
          {
              "_id": "60e30b684cb448de481a837a",
              "number": 22,
              "chrc": null,
              "sele": null,
              "ms": null,
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "super",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": null,
              "nnnnn": null,
              "file": null,
              "rat": null,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": null
          },
          {
              "_id": "60e30b704cb448de481a837d",
              "number": 23,
              "chrc": null,
              "sele": {
                  "color": "blue",
                  "value": "sss"
              },
              "ms": null,
              "phone": null,
              "emails": "a.aswara@gmail.com",
              "urls": "google.com",
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "aaaa",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": "2021-07-19T01:17:19.329Z",
              "nnnnn": null,
              "file": null,
              "rat": null,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          },
          {
              "_id": "60e30b794cb448de481a8380",
              "number": 24,
              "chrc": null,
              "sele": null,
              "ms": null,
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "asdasdada",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": null,
              "nnnnn": null,
              "file": null,
              "rat": null,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": null
          },
          {
              "_id": "60e30c004cb448de481a8382",
              "number": 25,
              "chrc": null,
              "sele": null,
              "ms": null,
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "asssss",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": null,
              "nnnnn": null,
              "file": null,
              "rat": null,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [
                  "60d5ae70bd50c764f65fbc21"
              ],
              "createdby": null,
              "updated": null
          },
          {
              "_id": "60e3337f4cb448de481a83a0",
              "number": 26,
              "chrc": true,
              "sele": null,
              "ms": null,
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "aaas",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": null,
              "nnnnn": null,
              "file": null,
              "rat": null,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": null
          },
          {
              "_id": "60e352fc4cb448de481a83a3",
              "number": 27,
              "chrc": null,
              "sele": null,
              "ms": null,
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "tessss",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": null,
              "nnnnn": null,
              "file": null,
              "rat": null,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [
                  "60d5aba0bd50c764f65fbc13"
              ],
              "createdby": null,
              "updated": null
          },
          {
              "_id": "60e3b1ef4cb448de481a83b2",
              "number": 28,
              "chrc": null,
              "sele": null,
              "ms": null,
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "asdsa",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": null,
              "nnnnn": null,
              "file": null,
              "rat": null,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": null
          },
          {
              "_id": "60e3d16b4cb448de481a83b4",
              "number": 29,
              "chrc": true,
              "sele": null,
              "ms": null,
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "aaa",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": null,
              "nnnnn": null,
              "file": null,
              "rat": null,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": null
          },
          {
              "_id": "60e3d3e54cb448de481a83b6",
              "number": 30,
              "chrc": true,
              "sele": null,
              "ms": [
                  {
                      "color": "blue",
                      "value": "aa"
                  }
              ],
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "sssss",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": "2021-07-17T00:36:39.920Z",
              "nnnnn": null,
              "file": null,
              "rat": null,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          },
          {
              "_id": "60e3d3e54cb448de481a83b8",
              "number": 31,
              "chrc": null,
              "sele": null,
              "ms": null,
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "aaa",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": null,
              "nnnnn": null,
              "file": null,
              "rat": null,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": null
          },
          {
              "_id": "60e5d7984cb448de481a84d3",
              "number": 32,
              "chrc": true,
              "sele": {
                  "color": "blue",
                  "value": "sss"
              },
              "ms": null,
              "phone": null,
              "emails": null,
              "urls": null,
              "currs": null,
              "perc": null,
              "rating": null,
              "durr": null,
              "Name": "tes",
              "sss": 12,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": "2021-07-19T01:16:59.509Z",
              "nnnnn": 4,
              "file": null,
              "rat": null,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          },
          {
              "_id": "60eeb455bcc3edbd3c1f0bee",
              "number": 33,
              "emails": null,
              "chrc": null,
              "sele": null,
              "ms": null,
              "urls": null,
              "perc": null,
              "durr": null,
              "currs": null,
              "rating": null,
              "phone": null,
              "Name": "asdsdsad",
              "sss": 15,
              "cre": "2021-07-15T03:59:34.914Z",
              "new": "sdassdsa",
              "update ats": "2021-07-19T01:18:17.328Z",
              "nnnnn": null,
              "file": null,
              "rat": 2,
              "note": null,
              "tanggal": "2021-07-15T01:16:00.000Z",
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          },
          {
              "_id": "60eff7e5bcc3edbd3c1f0c7f",
              "chrc": true,
              "durr": null,
              "sss": 12,
              "new": "sdassdsa",
              "emails": null,
              "cre": "2021-07-15T08:55:01.441Z",
              "sele": null,
              "number": 34,
              "urls": "",
              "currs": null,
              "rating": null,
              "ms": null,
              "phone": null,
              "perc": null,
              "Name": "ss",
              "update ats": "2021-07-19T01:16:53.264Z",
              "nnnnn": null,
              "file": null,
              "rat": null,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          },
          {
              "_id": "60eff7e8bcc3edbd3c1f0c81",
              "phone": null,
              "emails": null,
              "ms": null,
              "perc": null,
              "sss": 12,
              "new": "sdassdsa",
              "Name": "hallo",
              "chrc": null,
              "sele": null,
              "urls": null,
              "number": 35,
              "currs": null,
              "rating": null,
              "durr": null,
              "cre": "2021-07-15T08:55:04.774Z",
              "update ats": "2021-07-19T01:18:22.047Z",
              "nnnnn": null,
              "file": null,
              "rat": 1,
              "note": "hello dunia",
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          },
          {
              "_id": "60eff7efbcc3edbd3c1f0c83",
              "ms": null,
              "phone": null,
              "currs": null,
              "emails": null,
              "urls": null,
              "perc": null,
              "cre": "2021-07-15T08:55:11.195Z",
              "sss": 12,
              "new": "sdassdsa",
              "durr": null,
              "number": 36,
              "chrc": true,
              "sele": null,
              "rating": null,
              "Name": "hallo",
              "update ats": null,
              "nnnnn": null,
              "file": null,
              "rat": null,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": null
          },
          {
              "_id": "60f12e64bcc3edbd3c1f0cdf",
              "ms": null,
              "perc": null,
              "Name": "hallo",
              "chrc": null,
              "durr": null,
              "urls": null,
              "rating": null,
              "phone": null,
              "number": 37,
              "sele": null,
              "emails": null,
              "currs": null,
              "new": "sdassdsa",
              "sss": 12,
              "cre": "2021-07-16T06:59:48.684Z",
              "update ats": "2021-07-19T01:18:21.373Z",
              "nnnnn": null,
              "file": null,
              "rat": 2,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [
                  "60d698b10a5b7ac68c4a82bc"
              ],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          },
          {
              "_id": "60f12e6cbcc3edbd3c1f0ce1",
              "sele": null,
              "urls": null,
              "rating": null,
              "sss": 12,
              "ms": null,
              "emails": null,
              "currs": null,
              "durr": null,
              "cre": "2021-07-16T06:59:56.167Z",
              "new": "sdassdsa",
              "number": 38,
              "chrc": null,
              "phone": null,
              "perc": null,
              "Name": "sadsa",
              "update ats": "2021-07-19T01:17:52.039Z",
              "nnnnn": null,
              "file": null,
              "rat": null,
              "note": "selamat datang",
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [
                  "60d698b10a5b7ac68c4a82bc"
              ],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          },
          {
              "_id": "60f14795bcc3edbd3c1f0d5f",
              "phone": null,
              "durr": null,
              "sss": 12,
              "cre": "2021-07-16T08:47:17.452Z",
              "number": 39,
              "chrc": true,
              "ms": null,
              "currs": null,
              "perc": null,
              "sele": null,
              "emails": null,
              "Name": "hallo",
              "urls": null,
              "new": "sdassdsa",
              "rating": null,
              "update ats": "2021-07-16T10:45:49.472Z",
              "nnnnn": 12,
              "file": null,
              "rat": null,
              "note": null,
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": null,
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          },
          {
              "_id": "60f1c20271bb6eedc0e066e4",
              "number": 42,
              "new": "hello",
              "rat": 5,
              "urls": null,
              "Name": "hallo",
              "perc": null,
              "durr": null,
              "sss": 12,
              "chrc": null,
              "sele": null,
              "rating": null,
              "update ats": "2021-07-17T00:35:16.609Z",
              "file": null,
              "phone": null,
              "emails": null,
              "currs": null,
              "cre": "2021-07-16T17:29:38.986Z",
              "ms": null,
              "nnnnn": null,
              "note": "asss",
              "tanggal": null,
              "user": [],
              "email": [],
              "tes 2": [],
              "createdby": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              },
              "updated": {
                  "id": "6076f6154b4c4f8ee5c1e958",
                  "email": "a.aswara@gmail.com",
                  "firstName": "Adi Aswara",
                  "lastName": "aaa"
              }
          }
      ],
      "count": 30,
      "groupBy": {
          "rating": null
      }
  }
]